---
title: "tarea_4_r"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)

diamonds <- read.csv('diamonds.csv')
diamonds

```
1. Dispersión

```{r}

#1.1. Construya un gráfico de dispersión colocando en la estética carat (eje x) versus
#price(eje y), luego devuelva el gráfico.

qplot(carat,price,data=diamonds)

#1.2. Edite la estética y mapee el color con la variable clarity.

ggplot(diamonds, aes(carat, price, color=clarity)) + geom_point()

#1.3.Devuelva el gráfico con esta modificación

ggplot(diamonds, aes(carat, price, color=clarity)) + geom_point()

```
2. Histograma

```{r}

# 2.1. Construya el tipo de geometría histograma para la variable price. Configure el
#parámetro bins con el valor 40 y devuelva el gráfico.


ggplot(diamonds, aes(x=price)) + geom_histogram(bins = 40)

#2.2. Agregue una escala logarítmica de base 10 y devuelva el gráfico para ver la
#diferencia

ggplot(diamonds, aes(x=price)) + geom_histogram(bins = 40)+
  scale_x_log10()  

```

3. Boxplots

```{r}
#3.1. Construya un gráfico de cajas colocando en la estética la variable cut (eje x)
#versus price (eje y). Agregue una escala logarítmica por defecto y por último
#devuelva el gráfico.


ggplot(diamonds, aes(x=cut, y=price)) + 
  geom_boxplot()+
  scale_y_log10()


#3.2. Edite el color de cada caja con el parámetro fill dentro de la estética y asignando
#la variabl ecut. Por último devuelva el gráfico

ggplot(diamonds, aes(x=cut, y=price)) + 
  geom_boxplot(color="orange", fill="pink", alpha=0.2 ) +
  scale_y_log10()


```
4. Faceting

```{r}

#4.1. Filtre diamonds por la variable price que sea mayor a 1000 y por cut que
#contenga las categorías Good, Ideal y Premium. Luego asigne el resultado a la
#variable filtered_price. 

diamonds_price_over_1000_cut_GIP <- diamonds %>%
	filter(price>1000) %>%
  filter(cut %in% c('Good','Ideal', 'Premium'))

diamonds_price_over_1000_cut_GIP

filtered_price <- diamonds_prive_over_1000_cut_GIP

#4.2. Utilice la variable filtered_price para construir un gráfico de barras, en la estética
#configure x = cut, y = depth.
ggplot(filtered_price, aes(x=cut, y=depth)) + geom_col()

#4.3. Por último aplique faceting para la variable clarity y devuelva la parcela de
#gráficos.
ggplot(filtered_price, aes(x=cut, y=depth)) + geom_col()  +
  facet_wrap(~clarity)

#4.4. Edite la estética y configure el parámetro fill con la variable clarity. Luego
#devuelva la parcela de gráficos con esta modificación.  

ggplot(filtered_price, aes(x=cut, y=depth, fill=clarity)) + geom_col()  +
  facet_wrap(~clarity)
  

```

5. Grouping and summarizing

```{r}

#1. Utilice diamonds para construir un agrupamiento por la variable cut, luego aplique
#summarize para encontrar la media de las variables x, y, z (los nombres de los valores
#sumarizados serán mediaX, mediaY, mediaZ, respectivamente). Asigne el resultado a la
#variable median_dimension_diamond, por último imprima la variable.


#2. Utilice diamonds para filtrar por la variable cut igual a Premium. Luego agrupe por la
#variable clarity y utilice summarize para encontrar minimo y maximo de price (los
#nombres de los valores sumarizados serán minPrice y maxPrice, respectivamente).
#Asigne el resultado a la variable cut_premium e imprima el valor de la variable.


#3. Construya un gráfico de barras y utilice cut_premium como set de datos, configure
#x=clarity, y=maxPrice y el color de relleno (fill) con la variable clarity. Por último
#devuelva el gráfico.



```

